name = "LevelDB2"
uuid = "002418b5-1437-4398-8918-fc420664f8a4"
authors = ["Eric S. Tellez <donsadit@gmail.com>", "jerryzhenleicai@users.noreply.github.com", "Guido Kraemer <gdkrmr@users.noreply.github.com>"]
version = "1.0.0"

[deps]
LevelDB_jll = "e5add9ea-9f03-521a-be84-f8c1bde3cbe9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
LevelDB_jll = "1.22"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
